import AVFoundation
import Foundation

// Snapshot-style expected expansion helper used by macro-testing exact-output assertions.
func expectedMacroExpansion(
    classDeclaration: String,
    additionalTypeMembers: [String] = [],
    includeSendableExtension: Bool
) -> String {
    var lines: [String] = []

    lines.append("\(classDeclaration) {")
    lines.append("    let item: AVPlayerItem")
    if !additionalTypeMembers.isEmpty {
        for member in additionalTypeMembers {
            lines.append("    \(member)")
        }
    }
    lines.append("")
    lines.append("    /// A normalized diagnostics event emitted from AVPlayerItem failure surfaces.")
    lines.append("    enum PlaybackDiagnosticEvent: Sendable, CustomStringConvertible {")
    lines.append("        /// Emitted when playback fails to reach end time.")
    lines.append("        case failedToPlayToEnd(PlaybackFailureContext)")
    lines.append("        /// Emitted when a new AVPlayerItem error-log entry is recorded.")
    lines.append("        case newErrorLogEntry(PlaybackFailureContext)")
    lines.append("        /// Emitted when a new AVPlayerItem access-log entry is recorded.")
    lines.append("        case newAccessLogEntry(PlaybackFailureContext)")
    lines.append("")
    lines.append("        /// The captured diagnostics context associated with this event.")
    lines.append("        var context: PlaybackFailureContext {")
    lines.append("            switch self {")
    lines.append("            case let .failedToPlayToEnd(context),")
    lines.append("                 let .newErrorLogEntry(context),")
    lines.append("                 let .newAccessLogEntry(context):")
    lines.append("                return context")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        /// A stable case label for UI and logging surfaces.")
    lines.append("        var label: String {")
    lines.append("            switch self {")
    lines.append("            case .failedToPlayToEnd:")
    lines.append("                return \"failedToPlayToEnd\"")
    lines.append("            case .newErrorLogEntry:")
    lines.append("                return \"newErrorLogEntry\"")
    lines.append("            case .newAccessLogEntry:")
    lines.append("                return \"newAccessLogEntry\"")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        var description: String {")
    lines.append("            switch self {")
    lines.append("            case let .failedToPlayToEnd(context):")
    lines.append("                return \"failedToPlayToEnd(\\(context))\"")
    lines.append("            case let .newErrorLogEntry(context):")
    lines.append("                return \"newErrorLogEntry(\\(context))\"")
    lines.append("            case let .newAccessLogEntry(context):")
    lines.append("                return \"newAccessLogEntry(\\(context))\"")
    lines.append("            }")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    /// Captures a diagnostics snapshot from AVPlayerItem failure and log surfaces.")
    lines.append("    struct PlaybackFailureContext: Sendable, CustomStringConvertible {")
    lines.append("        /// Canonical diagnostics health states.")
    lines.append("        enum HealthState: String, Sendable {")
    lines.append("            case healthy")
    lines.append("            case failure")
    lines.append("        }")
    lines.append("")
    lines.append("        /// The current `item.error` value.")
    lines.append("        let itemError: Error?")
    lines.append("        /// The error payload received from failed-to-end notification user info.")
    lines.append("        let failedToPlayToEndError: Error?")
    lines.append("        /// Count of `errorLog` events at capture time.")
    lines.append("        let errorLogEventCount: Int")
    lines.append("        /// Count of `accessLog` events at capture time.")
    lines.append("        let accessLogEventCount: Int")
    lines.append("")
    lines.append("        /// Creates a diagnostics snapshot from the AVPlayerItem diagnostics surfaces.")
    lines.append("        static func capture(item: AVPlayerItem, failedToPlayToEndError: Error?) -> Self {")
    lines.append("            Self(")
    lines.append("                itemError: item.error,")
    lines.append("                failedToPlayToEndError: failedToPlayToEndError,")
    lines.append("                errorLogEventCount: item.errorLog()?.events.count ?? 0,")
    lines.append("                accessLogEventCount: item.accessLog()?.events.count ?? 0")
    lines.append("            )")
    lines.append("        }")
    lines.append("")
    lines.append("        /// The first error to surface, preferring failed-to-end payloads.")
    lines.append("        var primaryError: Error? {")
    lines.append("            failedToPlayToEndError ?? itemError")
    lines.append("        }")
    lines.append("")
    lines.append("        /// Indicates whether any failure surface currently reports an error.")
    lines.append("        var hasFailure: Bool {")
    lines.append("            primaryError != nil")
    lines.append("        }")
    lines.append("")
    lines.append("        /// The strongly typed health state derived from current failure surfaces.")
    lines.append("        var healthState: HealthState {")
    lines.append("            hasFailure ? .failure : .healthy")
    lines.append("        }")
    lines.append("")
    lines.append("        /// A short health label for display surfaces.")
    lines.append("        var healthLabel: String {")
    lines.append("            healthState.rawValue")
    lines.append("        }")
    lines.append("")
    lines.append("        /// A compact summary suitable for diagnostics panels.")
    lines.append("        var summary: String {")
    lines.append("            \"\\(healthLabel) | error log entries: \\(errorLogEventCount) | access log entries: \\(accessLogEventCount)\"")
    lines.append("        }")
    lines.append("")
    lines.append("        /// A compact single-line error summary.")
    lines.append("        var errorSummary: String {")
    lines.append("            guard let primaryError else {")
    lines.append("                return \"none\"")
    lines.append("            }")
    lines.append("            return String(String(describing: primaryError).prefix(120))")
    lines.append("        }")
    lines.append("")
    lines.append("        var description: String {")
    lines.append("            \"PlaybackFailureContext(itemError: \\(String(describing: itemError)), failedToPlayToEndError: \\(String(describing: failedToPlayToEndError)), errorLogEventCount: \\(errorLogEventCount), accessLogEventCount: \\(accessLogEventCount))\"")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    /// The most recent captured playback diagnostics snapshot.")
    lines.append("    ///")
    lines.append("    /// This snapshot updates for every diagnostics event, including log entries.")
    lines.append("    /// - Important: Read this property from the main actor.")
    lines.append("    private(set) var latestDiagnosticsContext: PlaybackFailureContext")
    lines.append("")
    lines.append("    /// The most recent captured playback failure snapshot.")
    lines.append("    ///")
    lines.append("    /// This value remains `nil` until a failure is observed on a failure surface.")
    lines.append("    /// Once set, it is sticky and only changes when a newer failure snapshot is captured.")
    lines.append("    /// - Important: Read this property from the main actor.")
    lines.append("    private(set) var latestFailureContext: PlaybackFailureContext?")
    lines.append("")
    lines.append("    /// A stream of normalized playback diagnostics events.")
    lines.append("    ///")
    lines.append("    /// - Important: Consume this stream from the main actor.")
    lines.append("    let playbackDiagnostics: AsyncStream<PlaybackDiagnosticEvent>")
    lines.append("")
    lines.append("    private let _diagnosticsContinuation: AsyncStream<PlaybackDiagnosticEvent>.Continuation")
    lines.append("")
    lines.append("    private var _notificationTokens: [NSObjectProtocol] = []")
    lines.append("")
    lines.append("    private func _emitDiagnostics(_ event: PlaybackDiagnosticEvent) {")
    lines.append("        let context = event.context")
    lines.append("        latestDiagnosticsContext = context")
    lines.append("        if context.hasFailure {")
    lines.append("            latestFailureContext = context")
    lines.append("        }")
    lines.append("        _diagnosticsContinuation.yield(event)")
    lines.append("    }")
    lines.append("")
    lines.append("    init(item: AVPlayerItem) {")
    lines.append("        // Phase 1: Stream setup.")
    lines.append("        self.item = item")
    lines.append("        let (playbackDiagnostics, diagnosticsContinuation) = AsyncStream<PlaybackDiagnosticEvent>.makeStream()")
    lines.append("        self.playbackDiagnostics = playbackDiagnostics")
    lines.append("        self._diagnosticsContinuation = diagnosticsContinuation")
    lines.append("")
    lines.append("        // Phase 2: Initial snapshot capture.")
    lines.append("        let initialContext = PlaybackFailureContext.capture(item: item, failedToPlayToEndError: nil)")
    lines.append("        self.latestDiagnosticsContext = initialContext")
    lines.append("        self.latestFailureContext = if initialContext.hasFailure {")
    lines.append("            initialContext")
    lines.append("        } else {")
    lines.append("            nil")
    lines.append("        }")
    lines.append("")
    lines.append("        // Phase 3: Notification observers.")
    lines.append("        let _failedToEndNotificationToken = NotificationCenter.default.addObserver(forName: AVPlayerItem.failedToPlayToEndTimeNotification, object: item, queue: .main) { [weak self] notification in")
    lines.append("            let failedToPlayToEndError = notification.userInfo.flatMap { userInfo in")
    lines.append("                userInfo[AVPlayerItemFailedToPlayToEndTimeErrorKey] as? NSError")
    lines.append("            }")
    lines.append("            // Hop onto the main actor before mutating diagnostics state.")
    lines.append("            Task { @MainActor [weak self, failedToPlayToEndError] in")
    lines.append("                guard let self else {")
    lines.append("                    return")
    lines.append("                }")
    lines.append("                let context = PlaybackFailureContext.capture(item: self.item, failedToPlayToEndError: failedToPlayToEndError)")
    lines.append("                self._emitDiagnostics(.failedToPlayToEnd(context))")
    lines.append("            }")
    lines.append("        }")
    lines.append("        self._notificationTokens.append(_failedToEndNotificationToken)")
    lines.append("        let _newErrorLogEntryNotificationToken = NotificationCenter.default.addObserver(forName: AVPlayerItem.newErrorLogEntryNotification, object: item, queue: .main) { [weak self] _ in")
    lines.append("            // Hop onto the main actor before mutating diagnostics state.")
    lines.append("            Task { @MainActor [weak self] in")
    lines.append("                guard let self else {")
    lines.append("                    return")
    lines.append("                }")
    lines.append("                let failedToPlayToEndError = self.latestFailureContext?.failedToPlayToEndError")
    lines.append("                let context = PlaybackFailureContext.capture(item: self.item, failedToPlayToEndError: failedToPlayToEndError)")
    lines.append("                self._emitDiagnostics(.newErrorLogEntry(context))")
    lines.append("            }")
    lines.append("        }")
    lines.append("        self._notificationTokens.append(_newErrorLogEntryNotificationToken)")
    lines.append("        let _newAccessLogEntryNotificationToken = NotificationCenter.default.addObserver(forName: AVPlayerItem.newAccessLogEntryNotification, object: item, queue: .main) { [weak self] _ in")
    lines.append("            // Hop onto the main actor before mutating diagnostics state.")
    lines.append("            Task { @MainActor [weak self] in")
    lines.append("                guard let self else {")
    lines.append("                    return")
    lines.append("                }")
    lines.append("                let failedToPlayToEndError = self.latestFailureContext?.failedToPlayToEndError")
    lines.append("                let context = PlaybackFailureContext.capture(item: self.item, failedToPlayToEndError: failedToPlayToEndError)")
    lines.append("                self._emitDiagnostics(.newAccessLogEntry(context))")
    lines.append("            }")
    lines.append("        }")
    lines.append("        self._notificationTokens.append(_newAccessLogEntryNotificationToken)")
    lines.append("    }")
    lines.append("")
    lines.append("    isolated deinit {")
    lines.append("        for token in _notificationTokens {")
    lines.append("            NotificationCenter.default.removeObserver(token)")
    lines.append("        }")
    lines.append("        _diagnosticsContinuation.finish()")
    lines.append("    }")
    lines.append("}")

    if includeSendableExtension {
        lines.append("")
        lines.append("extension PlayerDiagnostics: Sendable {")
        lines.append("}")
    }

    return lines.joined(separator: "\n")
}
